name: ci_cd

on:
  push:
    branches:
      - main
        
jobs:
  build:
    name: 测试
    uses: deming-org/share_workflows/.github/workflows/workflow-1.yml@main
    with:
      config-path: '/1.yml'
    secrets: inherit

    
    
      

          
